# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: react-storefront-boilerplate

package:
  individually: true
  exclude:
    - "**"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

plugins:
  - serverless-offline
  # - serverless-domain-manager

# The `functions` block defines what code to deploy
functions:
  app:
    handler: serverless/dist/app.handler
    memorySize: 1536
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /{any+}
          method: get
          cors: true
    package:
      archive: dist/packages/app.zip
      include: 
        - serverless/dist/app.js
        - serverless/dist/app.js.map
        - build/**/*
# custom:
#   customDomain:
#     domainName: serverless-rsf.moovweb.cloud
#     stage: dev
#     basePath: /
#     certificateName: '*.moovweb.cloud'
#     createRoute53Record: true
#     endpointType: 'regional'