# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: react-storefront-boilerplate

package:
  individually: true
  exclude:
    - "**"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-domain-manager
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'

custom:
  domains:
    production: rsf-lambda-poc.moovweb-dev.net
    dev: rsf-lambda-poc.moovweb-dev.net
  customDomain:
    domainName: '${self:custom.domains.${self:provider.stage}}'
    basePath: '/'
    stage: ${self:provider.stage}
    createRoute53Record: true
    # certificateName: "rsf-lambda-poc.moovweb-dev.net"

functions:
  edge:
    name: '${self:custom.objectPrefix}-edge'
    handler: serverless/dist/edge.handler
    memorySize: 128
    timeout: 1
    lambdaAtEdge:
      distribution: 'WebsiteDistribution'
      eventType: 'origin-request'
  app:
    handler: serverless/dist/app.handler
    memorySize: 1536
    events:
      - http:
          path: /{any+}
          method: any
          cors: true
      - http:
          path: /
          method: any
          cors: true
    package:
      archive: dist/packages/app.zip
      include: 
        - serverless/dist/app.js
        - serverless/dist/app.js.map
        - build/**/*

# custom:
#   customDomain:
#     domainName: serverless-rsf.moovweb.cloud
#     stage: dev
#     basePath: /
#     certificateName: '*.moovweb.cloud'
#     createRoute53Record: true
#     endpointType: 'regional'