# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: react-storefront-boilerplate

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - "**"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
plugins:
  - serverless-offline
  # - serverless-domain-manager
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'

# custom:
#   customDomain:
#     domainName: rsf-lambda-poc.moovweb-dev.net
#     basePath: ''
#     createRoute53Record: true
#     certificateName: "rsf-lambda-poc.moovweb-dev.net"

functions:
  edge:
    handler: serverless/dist/edge.handler
    memorySize: 128
    timeout: 1
    lambdaAtEdge:
      distribution: WebsiteDistribution
      eventType: 'viewer-request'
    package:
      archive: dist/packages/edge.zip
      include:
        - serverless/dist/edge.js
        - serverless/dist/edge.js.map

  app:
    handler: serverless/dist/app.handler
    memorySize: 1536
    events:
      - http:
          path: /{any+}
          method: any
          cors: true
      - http:
          path: /
          method: any
          cors: true
    package:
      archive: dist/packages/app.zip
      include:
        - serverless/dist/app.js
        - serverless/dist/app.js.map
        - build/**/*

resources:
  Resources:
    WebsiteDistribution:
        Type: 'AWS::CloudFront::Distribution'
        Properties:
          DistributionConfig:
              DefaultCacheBehavior:
                TargetOriginId: 'RSF-Lambda'
                ViewerProtocolPolicy: 'redirect-to-https'
                Compress: true
                ForwardedValues:
                    Headers:
                      - x-moov-cache-hash
                    QueryString: true
                    QueryStringCacheKeys: []
                    Cookies:
                      Forward: 'all'
              Enabled: true
              HttpVersion: 'http2'
              ViewerCertificate:
                CloudFrontDefaultCertificate: true
              Origins:
                -
                  Id: RSF-Lambda
                  DomainName: ebr04ic2h7.execute-api.us-east-1.amazonaws.com #{ 'Fn::Join': [ '', ['https://', { 'Ref': 'ApiGatewayRestApi' }, '.execute-api.us-east-1.', { 'Ref': 'AWS::URLSuffix' }]] }
                  OriginPath: /production
                  CustomOriginConfig:
                    HTTPPort: 80
                    HTTPSPort: 443
                    OriginProtocolPolicy: 'https-only'