# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: react-storefront-boilerplate

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - "**"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: rsf-lambda-poc.moovweb-dev.net
    basePath: ''
    createRoute53Record: true
    certificateName: "rsf-lambda-poc.moovweb-dev.net"

functions:
  app:
    handler: serverless/dist/app.handler
    memorySize: 1536
    events:
      - http:
          path: /{any+}
          method: any
          cors: true
      - http:
          path: /
          method: any
          cors: true
    package:
      archive: dist/packages/app.zip
      include:
        - serverless/dist/app.js
        - serverless/dist/app.js.map
        - build/**/*